[package]
name = "pacom"
version = "0.1.0"
edition = "2024"
description = "A Platform Agnostic Communication Middleware for uProtocol and SDV"
authors = ["Paolo Galiano Bove"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/PaoloGalianoBove/pacom"
keywords = ["automotive", "uprotocol", "sdv", "vsomeip", "mqtt"]
categories = ["network-programming", "aerospace-and-automotive"]
[dependencies]
tokio = { version = "1", features = ["full"] }
up-rust = "0.9.0"
up-transport-vsomeip = { git = "https://github.com/eclipse-uprotocol/up-transport-vsomeip-rust.git", package = "up-transport-vsomeip" }
up-transport-mqtt5 = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
log = "0.4"
async-trait = "0.1"
thiserror = "2"
sysinfo = { version = "0.37.2", default-features = false, features = ["system"] }

[[example]]
name = "rtt_server"
path = "examples/rtt/server/main.rs"

[[example]]
name = "rtt_client"
path = "examples/rtt/client/main.rs"

[[example]]
name = "mqtt_bridge_edge"
path = "examples/mqtt_bridge/edge/main.rs"

[[example]]
name = "mqtt_bridge_hub"
path = "examples/mqtt_bridge/hub/main.rs"

[[example]]
name = "mqtt_bridge_probe"
path = "examples/mqtt_bridge/probe/main.rs"

[[example]]
name = "mqtt_bridge_sender"
path = "examples/mqtt_bridge/sender/main.rs"
